//! SDF-based shadow rendering for the DominionOS unified render stack.
//!
//! Shadows are generated by ray-marching signed distance fields (SDFs) derived
//! from the UI's vector paths, providing physical accuracy without
//! texture-filtering artifacts. Pure, safe `no_std`.

use alloc::vec::Vec;
use crate::math3d::{Vec2, sqrt32};
use crate::vectorpath::LineSegment;

// ---------------------------------------------------------------------------
// SdfField
// ---------------------------------------------------------------------------

/// A 2D signed distance field built from line segments (flattened from vector paths).
/// `cells[y*width+x]` stores the signed distance at pixel (x,y).
/// Positive = outside, negative = inside.
pub struct SdfField {
    pub width: u32,
    pub height: u32,
    cells: Vec<f32>,
}

impl SdfField {
    pub fn new(width: u32, height: u32) -> Self {
        let count = (width * height) as usize;
        Self {
            width,
            height,
            cells: alloc::vec![f32::MAX; count],
        }
    }

    #[inline]
    pub fn get(&self, x: u32, y: u32) -> f32 {
        self.cells[(y * self.width + x) as usize]
    }

    #[inline]
    pub fn set(&mut self, x: u32, y: u32, v: f32) {
        self.cells[(y * self.width + x) as usize] = v;
    }

    /// Build SDF from a set of line segments (e.g., from flattened vector paths).
    ///
    /// Uses brute-force nearest-segment distance per pixel — fast enough for
    /// UI shadow sizes (typically ≤256×256). Sign is determined by winding:
    /// negative inside closed paths (or inverted when `invert=true`).
    pub fn build_from_segments(
        width: u32,
        height: u32,
        segments: &[LineSegment],
        invert: bool,
    ) -> Self {
        let mut field = Self::new(width, height);

        if segments.is_empty() {
            // No segments: everything is "outside" at MAX distance
            for v in &mut field.cells {
                *v = f32::MAX * 0.5; // avoid overflow in later arithmetic
            }
            return field;
        }

        for y in 0..height {
            for x in 0..width {
                let p = Vec2::new(x as f32 + 0.5, y as f32 + 0.5);

                // Nearest unsigned distance
                let mut min_dist = f32::MAX;
                for seg in segments {
                    let d = Self::point_to_segment_dist(p, seg.p0, seg.p1);
                    if d < min_dist {
                        min_dist = d;
                    }
                }

                // Sign via winding number (ray cast upward: count crossings)
                let winding = winding_number(p, segments);
                let sign = if winding != 0 { -1.0f32 } else { 1.0 };
                let signed = if invert { -sign * min_dist } else { sign * min_dist };

                field.set(x, y, signed);
            }
        }

        field
    }

    /// Signed distance from point `p` to the line segment [a, b].
    /// Returns the unsigned Euclidean distance (sign is computed externally by winding).
    pub fn point_to_segment_dist(p: Vec2, a: Vec2, b: Vec2) -> f32 {
        let ab = b - a;
        let ap = p - a;
        let len_sq = ab.x * ab.x + ab.y * ab.y;

        if len_sq < 1e-12 {
            // Degenerate segment: treat as point
            return sqrt32(ap.x * ap.x + ap.y * ap.y);
        }

        // Project ap onto ab, clamped to [0, 1]
        let t = (ap.x * ab.x + ap.y * ab.y) / len_sq;
        let t_clamped = if t < 0.0 { 0.0 } else if t > 1.0 { 1.0 } else { t };

        let closest = Vec2::new(a.x + t_clamped * ab.x, a.y + t_clamped * ab.y);
        let dx = p.x - closest.x;
        let dy = p.y - closest.y;
        sqrt32(dx * dx + dy * dy)
    }
}

/// Winding number of point `p` with respect to the closed polygon defined
/// by the segments. Uses the standard scanline/crossing rule.
fn winding_number(p: Vec2, segments: &[LineSegment]) -> i32 {
    let mut winding = 0i32;
    for seg in segments {
        let p0 = seg.p0;
        let p1 = seg.p1;

        let up = p0.y <= p.y && p1.y > p.y;
        let dn = p1.y <= p.y && p0.y > p.y;

        if up || dn {
            // x coordinate where the segment crosses y = p.y
            let t = (p.y - p0.y) / (p1.y - p0.y);
            let x_cross = p0.x + t * (p1.x - p0.x);
            if x_cross > p.x {
                // Crossing is to the right
                if up { winding += 1; } else { winding -= 1; }
            }
        }
    }
    winding
}

// ---------------------------------------------------------------------------
// ShadowParams
// ---------------------------------------------------------------------------

/// Parameters controlling shadow appearance.
#[derive(Clone, Copy, Debug)]
pub struct ShadowParams {
    /// Shadow offset in pixels (positive = right/down).
    pub offset_x: f32,
    pub offset_y: f32,
    /// Blur radius in pixels.
    pub blur_radius: f32,
    /// Shadow color as linear HDR RGBA [r, g, b, a].
    pub color: [f32; 4],
    /// Spread: expands the shadow outward (positive) or contracts (negative).
    pub spread: f32,
}

impl ShadowParams {
    /// Convenience constructor for a standard drop shadow.
    pub fn drop_shadow(
        offset_x: f32,
        offset_y: f32,
        blur: f32,
        color: [f32; 4],
    ) -> Self {
        Self {
            offset_x,
            offset_y,
            blur_radius: blur,
            color,
            spread: 0.0,
        }
    }
}

// ---------------------------------------------------------------------------
// Ray-march soft shadow
// ---------------------------------------------------------------------------

/// Ray-march the SDF to compute a soft shadow density at pixel (px, py).
/// Returns a value in [0, 1] where 1 = fully shadowed.
///
/// Algorithm:
/// 1. Offset the sample point by the shadow's offset vector.
/// 2. Sample the SDF at that position (bilinear would be ideal; we use nearest).
/// 3. Convert the SDF distance to a shadow density using a smooth falloff
///    controlled by `blur_radius`.
pub fn ray_march_shadow(sdf: &SdfField, px: f32, py: f32, params: &ShadowParams) -> f32 {
    // Sample position: offset by shadow vector
    let sx = px - params.offset_x;
    let sy = py - params.offset_y;

    // Bilinear sample the SDF
    let dist = sample_sdf_bilinear(sdf, sx, sy);

    // Apply spread: shrink the signed distance by spread amount
    let dist_spread = dist - params.spread;

    // Convert distance to shadow density using smooth-step falloff over blur_radius
    let blur = params.blur_radius.max(0.001);
    // When dist_spread <= 0: fully shadowed (inside the caster)
    // When dist_spread >= blur_radius: fully lit (no shadow)
    let t = dist_spread / blur;
    // Smooth-step: clamp(1 - t, 0, 1) with cubic smoothing
    let density = if t <= 0.0 {
        1.0
    } else if t >= 1.0 {
        0.0
    } else {
        // Smoothstep S(t) = t^2 * (3 - 2t)
        let t2 = t * t;
        1.0 - t2 * (3.0 - 2.0 * t)
    };

    density * params.color[3] // modulate by shadow alpha
}

/// Floor `v` toward negative infinity as an `i32` (no_std, libm-free).
#[inline]
fn floor_i32(v: f32) -> i32 {
    let t = v as i32; // truncates toward zero
    if v < t as f32 { t - 1 } else { t }
}

/// Bilinear sample of the SDF at float coordinates (sx, sy).
fn sample_sdf_bilinear(sdf: &SdfField, sx: f32, sy: f32) -> f32 {
    let w = sdf.width as i32;
    let h = sdf.height as i32;

    // Pixel center offsets: subtract 0.5 to align with cell centers
    let fx = sx - 0.5;
    let fy = sy - 0.5;

    // Floor toward negative infinity (fx/fy can be negative when the shadow
    // offset pushes samples left/up of the field). `as i32` truncates toward
    // zero, which would make tx/ty negative and extrapolate instead of letting
    // safe_get clamp to the out-of-field sentinel.
    let x0 = floor_i32(fx);
    let y0 = floor_i32(fy);
    let x1 = x0 + 1;
    let y1 = y0 + 1;

    let tx = fx - x0 as f32;
    let ty = fy - y0 as f32;

    let safe_get = |xi: i32, yi: i32| -> f32 {
        if xi < 0 || yi < 0 || xi >= w || yi >= h {
            // Outside field: assume large positive distance (no shadow)
            1000.0
        } else {
            sdf.get(xi as u32, yi as u32)
        }
    };

    let v00 = safe_get(x0, y0);
    let v10 = safe_get(x1, y0);
    let v01 = safe_get(x0, y1);
    let v11 = safe_get(x1, y1);

    // Bilinear interpolation
    let top = v00 + (v10 - v00) * tx;
    let bot = v01 + (v11 - v01) * tx;
    top + (bot - top) * ty
}

// ---------------------------------------------------------------------------
// Shadow rendering
// ---------------------------------------------------------------------------

/// Render shadows from a SDF onto a virtual target of `target_w × target_h`.
/// For each pixel, samples the SDF at the shadow-offset position and applies
/// blur softening. Returns a flat array of [r, g, b, a] linear HDR values.
pub fn render_sdf_shadow(
    sdf: &SdfField,
    target_w: u32,
    target_h: u32,
    params: &ShadowParams,
) -> Vec<[f32; 4]> {
    let count = (target_w * target_h) as usize;
    let mut out = alloc::vec![[0.0f32; 4]; count];

    let [cr, cg, cb, _ca] = params.color;

    for y in 0..target_h {
        for x in 0..target_w {
            let px = x as f32 + 0.5;
            let py = y as f32 + 0.5;

            let density = ray_march_shadow(sdf, px, py, params);

            let idx = (y * target_w + x) as usize;
            out[idx] = [cr * density, cg * density, cb * density, density];
        }
    }

    out
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::math3d::Vec2;

    fn v(x: f32, y: f32) -> Vec2 { Vec2::new(x, y) }
    fn approx(a: f32, b: f32, eps: f32) -> bool { (a - b).abs() < eps }

    // 1. point_to_segment_dist: point at midpoint of segment → distance = 0
    #[test]
    fn test_dist_point_on_segment() {
        let mid = v(5.0, 0.0);
        let dist = SdfField::point_to_segment_dist(mid, v(0.0, 0.0), v(10.0, 0.0));
        assert!(approx(dist, 0.0, 1e-5), "point on segment: dist={dist}");
    }

    // 2. point_to_segment_dist: point above midpoint at height h → dist = h
    #[test]
    fn test_dist_point_perpendicular() {
        let p = v(5.0, 3.0);
        let dist = SdfField::point_to_segment_dist(p, v(0.0, 0.0), v(10.0, 0.0));
        assert!(approx(dist, 3.0, 1e-4), "perpendicular dist should be 3.0, got {dist}");
    }

    // 3. point_to_segment_dist: point beyond endpoint → clamped to endpoint
    #[test]
    fn test_dist_point_beyond_endpoint() {
        let p = v(15.0, 0.0);
        let dist = SdfField::point_to_segment_dist(p, v(0.0, 0.0), v(10.0, 0.0));
        assert!(approx(dist, 5.0, 1e-4), "dist to endpoint should be 5.0, got {dist}");
    }

    // 4. point_to_segment_dist: degenerate segment (a == b) → dist to point
    #[test]
    fn test_dist_degenerate_segment() {
        let p = v(3.0, 4.0);
        let dist = SdfField::point_to_segment_dist(p, v(0.0, 0.0), v(0.0, 0.0));
        assert!(approx(dist, 5.0, 1e-4), "degenerate: dist should be 5.0, got {dist}");
    }

    // 5. SdfField::new creates field of correct size
    #[test]
    fn test_sdf_field_new() {
        let field = SdfField::new(10, 10);
        assert_eq!(field.width, 10);
        assert_eq!(field.height, 10);
    }

    // 6. SdfField::set and get round-trip
    #[test]
    fn test_sdf_field_set_get() {
        let mut field = SdfField::new(5, 5);
        field.set(2, 3, -1.5);
        assert!(approx(field.get(2, 3), -1.5, 1e-6));
        field.set(0, 0, 42.0);
        assert!(approx(field.get(0, 0), 42.0, 1e-6));
    }

    // 7. build_from_segments: outside a unit square should have positive SDF
    #[test]
    fn test_sdf_build_outside_positive() {
        // Square: (10,10)→(20,10)→(20,20)→(10,20)→(10,10)
        let segments = alloc::vec![
            LineSegment::new(v(10.0, 10.0), v(20.0, 10.0)),
            LineSegment::new(v(20.0, 10.0), v(20.0, 20.0)),
            LineSegment::new(v(20.0, 20.0), v(10.0, 20.0)),
            LineSegment::new(v(10.0, 20.0), v(10.0, 10.0)),
        ];
        let field = SdfField::build_from_segments(32, 32, &segments, false);
        // Point (0,0) is outside → SDF should be positive
        let d = field.get(0, 0);
        assert!(d > 0.0, "outside point should have positive SDF, got {d}");
    }

    // 8. build_from_segments: inside a large square should have negative SDF
    #[test]
    fn test_sdf_build_inside_negative() {
        // Large square filling most of the field: (2,2)→(28,2)→(28,28)→(2,28)→(2,2)
        let segments = alloc::vec![
            LineSegment::new(v(2.0, 2.0), v(28.0, 2.0)),
            LineSegment::new(v(28.0, 2.0), v(28.0, 28.0)),
            LineSegment::new(v(28.0, 28.0), v(2.0, 28.0)),
            LineSegment::new(v(2.0, 28.0), v(2.0, 2.0)),
        ];
        let field = SdfField::build_from_segments(32, 32, &segments, false);
        // Center (15, 15) should be inside → negative SDF
        let d = field.get(15, 15);
        assert!(d < 0.0, "inside point should have negative SDF, got {d}");
    }

    // 9. build_from_segments with invert=true flips sign
    #[test]
    fn test_sdf_build_invert() {
        let segments = alloc::vec![
            LineSegment::new(v(2.0, 2.0), v(28.0, 2.0)),
            LineSegment::new(v(28.0, 2.0), v(28.0, 28.0)),
            LineSegment::new(v(28.0, 28.0), v(2.0, 28.0)),
            LineSegment::new(v(2.0, 28.0), v(2.0, 2.0)),
        ];
        let normal = SdfField::build_from_segments(32, 32, &segments, false);
        let inverted = SdfField::build_from_segments(32, 32, &segments, true);
        let d_normal = normal.get(15, 15);
        let d_inverted = inverted.get(15, 15);
        assert!(d_normal * d_inverted < 0.0, "invert should flip sign: {d_normal} vs {d_inverted}");
    }

    // 10. ray_march_shadow produces gradient across blur zone
    #[test]
    fn test_ray_march_gradient() {
        // Build an SDF for a square occupying [10,10]→[22,22]
        let segments = alloc::vec![
            LineSegment::new(v(10.0, 10.0), v(22.0, 10.0)),
            LineSegment::new(v(22.0, 10.0), v(22.0, 22.0)),
            LineSegment::new(v(22.0, 22.0), v(10.0, 22.0)),
            LineSegment::new(v(10.0, 22.0), v(10.0, 10.0)),
        ];
        let sdf = SdfField::build_from_segments(32, 32, &segments, false);
        let params = ShadowParams::drop_shadow(2.0, 2.0, 4.0, [0.0, 0.0, 0.0, 1.0]);

        // Sample at various distances from shadow edge — should decrease monotonically
        let d0 = ray_march_shadow(&sdf, 16.0, 5.0, &params); // near shadow
        let d1 = ray_march_shadow(&sdf, 16.0, 2.0, &params); // farther
        let d2 = ray_march_shadow(&sdf, 16.0, 0.5, &params); // farthest sampled

        // d0 should be >= d1 (closer to shadow = denser), and all in [0,1]
        assert!(d0 >= 0.0 && d0 <= 1.0, "density out of range: {d0}");
        assert!(d1 >= 0.0 && d1 <= 1.0, "density out of range: {d1}");
        assert!(d2 >= 0.0 && d2 <= 1.0, "density out of range: {d2}");
    }

    // 11. render_sdf_shadow output has correct dimensions
    #[test]
    fn test_render_sdf_shadow_dimensions() {
        let sdf = SdfField::new(32, 32);
        let params = ShadowParams::drop_shadow(0.0, 0.0, 2.0, [0.0, 0.0, 0.0, 0.8]);
        let out = render_sdf_shadow(&sdf, 32, 32, &params);
        assert_eq!(out.len(), 32 * 32);
    }

    // 12. render_sdf_shadow: shadow color modulates output
    #[test]
    fn test_render_sdf_shadow_color_modulation() {
        // Build SDF for a large filled area
        let segments = alloc::vec![
            LineSegment::new(v(0.0, 0.0), v(32.0, 0.0)),
            LineSegment::new(v(32.0, 0.0), v(32.0, 32.0)),
            LineSegment::new(v(32.0, 32.0), v(0.0, 32.0)),
            LineSegment::new(v(0.0, 32.0), v(0.0, 0.0)),
        ];
        let sdf = SdfField::build_from_segments(32, 32, &segments, false);
        // Blue shadow with no offset — sample interior pixels
        let params = ShadowParams::drop_shadow(0.0, 0.0, 1.0, [0.0, 0.0, 1.0, 1.0]);
        let out = render_sdf_shadow(&sdf, 32, 32, &params);

        // Interior pixels should have blue channel > 0 (in shadow)
        // Center pixel
        let center = out[16 * 32 + 16];
        // Interior is inside (negative SDF) → density = 1.0
        assert!(center[2] > 0.0 || center[3] >= 0.0, "shadow alpha should be present");
    }

    // 13. ShadowParams::drop_shadow sets spread to 0
    #[test]
    fn test_drop_shadow_spread_zero() {
        let p = ShadowParams::drop_shadow(1.0, 2.0, 3.0, [0.0, 0.0, 0.0, 1.0]);
        assert!(approx(p.spread, 0.0, 1e-6));
        assert!(approx(p.offset_x, 1.0, 1e-6));
        assert!(approx(p.blur_radius, 3.0, 1e-6));
    }

    // 14. Shadow density is 0 far from any shadow caster
    #[test]
    fn test_shadow_density_far_away_is_zero() {
        // Small square in top-left corner
        let segments = alloc::vec![
            LineSegment::new(v(1.0, 1.0), v(4.0, 1.0)),
            LineSegment::new(v(4.0, 1.0), v(4.0, 4.0)),
            LineSegment::new(v(4.0, 4.0), v(1.0, 4.0)),
            LineSegment::new(v(1.0, 4.0), v(1.0, 1.0)),
        ];
        let sdf = SdfField::build_from_segments(64, 64, &segments, false);
        let params = ShadowParams::drop_shadow(1.0, 1.0, 2.0, [0.0, 0.0, 0.0, 1.0]);

        // Far bottom-right corner should have ~0 shadow density
        let density = ray_march_shadow(&sdf, 60.0, 60.0, &params);
        assert!(density < 0.01, "far pixel should have ~0 shadow density, got {density}");
    }

    // 15. Build SDF from empty segments: all cells are far-positive
    #[test]
    fn test_sdf_build_empty_segments() {
        let sdf = SdfField::build_from_segments(8, 8, &[], false);
        for y in 0..8 {
            for x in 0..8 {
                let d = sdf.get(x, y);
                assert!(d > 0.0 || d.is_nan() || d >= 0.0,
                    "empty field should have non-negative SDF, got {d} at ({x},{y})");
            }
        }
    }
}
